# numpy

In [2]:
import numpy as np

In [7]:
# array创建
a1 = np.array([0,1,2,3])
a2 = np.array(range(4))
a3 = np.arange(4)

In [8]:
print(a1,a2,a3)

[0 1 2 3] [0 1 2 3] [0 1 2 3]


In [11]:
# 查看数据类型
a2.dtype

dtype('int32')

In [13]:
a4 = np.array([1,2,3,4], dtype="float64")
print(a4.dtype)

float64


In [15]:
# 调整数据类型
a5 = a4.astype("int64")
a5.dtype

dtype('int64')

In [16]:
import random
a6 = np.array([random.random() for i in range(10)])
a6

array([0.24753274, 0.28388672, 0.059283  , 0.16640861, 0.83396244,
       0.26378873, 0.42305853, 0.17057602, 0.09575832, 0.46692972])

In [19]:
a6 = np.round(a6, 3)
a6

array([0.248, 0.284, 0.059, 0.166, 0.834, 0.264, 0.423, 0.171, 0.096,
       0.467])

In [23]:
# 查看形状
a7 = np.arange(5)
print(a7.shape)
a8 = np.array([[1,2,3],[1,3,4]])
print(a8.shape)

(5,)
(2, 3)


In [35]:
# 改变形状
a9=np.arange(24).reshape((2,3,4))
print(a9)
a10 = a9.flatten()
print(a10)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [6]:
# 转置
b1 = np.arange(24).reshape((6,4))
print(b1)
# 1
b2 = b1.transpose()
print(b2)
# 2
b3 = b1.swapaxes(1,0) # 交换0，1轴
print(b3)
# 3
b4 = b1.T
print(b4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


In [44]:
# 运算
b = np.array([[1,2,3],[1,3,4]])
c = np.array([1,2,3])
b+c

array([[2, 4, 6],
       [2, 5, 7]])

In [24]:
# 读取数据
t = np.loadtxt("./sample_submit.csv", delimiter=",", dtype = "int32", skiprows=1, usecols=(0,1,2,3))

In [25]:
t 

array([[100000,      0,      0,      0],
       [100001,      0,      0,      0],
       [100002,      0,      0,      0],
       ...,
       [119997,      0,      0,      0],
       [119998,      0,      0,      0],
       [119999,      0,      0,      0]])

In [38]:
# 取数据
# 取一行
print(t[2, :])
# 去多行
print(t[2:5, :])
# 取不连续的行
print(t[[1,4,6],:])

# 取一列
print(t[:, 2])
# 取多列
print(t[:, 2:5])
# 取不连续的列
print(t[:, [1,2,3]])

# 取多行多列
print(t[3:6, 0:2])
print(t[[1,3,5], [0,2,3]])

[100002      0      0      0]
[[100002      0      0      0]
 [100003      0      0      0]
 [100004      0      0      0]]
[[100001      0      0      0]
 [100004      0      0      0]
 [100006      0      0      0]]
[0 0 0 ... 0 0 0]
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 ...
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[100003      0]
 [100004      0]
 [100005      0]]
[100001      0      0]


In [40]:
# 修改数据
d = np.arange(24).reshape((6,4))
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [45]:
d[3,3] = 10000
d

array([[    0,     1,     2,     3],
       [    4,     5,     6,     7],
       [    8,     9,    10,    11],
       [   12,    13,    14, 10000],
       [   16,    17,    18,    19],
       [   20,    21,    22,    23]])

In [46]:
d[d<10] = 0
d

array([[    0,     0,     0,     0],
       [    0,     0,     0,     0],
       [    0,     0,    10,    11],
       [   12,    13,    14, 10000],
       [   16,    17,    18,    19],
       [   20,    21,    22,    23]])

In [49]:
d2 = np.where(d<10, -1, 100)
d2

array([[ -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1],
       [ -1,  -1, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [50]:
d3 = d.clip(10, 18)
d3

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 11],
       [12, 13, 14, 18],
       [16, 17, 18, 18],
       [18, 18, 18, 18]])

In [5]:
# 拼接
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([11,13,32,34,54,6])
c = np.vstack([a, b])
print(c)
c2  =np.hstack([a, b])
print(c2)

[[ 1  2  3  4  5  6]
 [11 13 32 34 54  6]]
[ 1  2  3  4  5  6 11 13 32 34 54  6]


In [8]:
# 获取最大最小值索引
d = np.arange(24).reshape(4,6)
print(d)
np.argmax(d, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([3, 3, 3, 3, 3, 3], dtype=int64)

In [9]:
np.argmin(d, axis=1)

array([0, 0, 0, 0], dtype=int64)

In [13]:
# 随机数
np.random.randn(2,3)

array([[-0.39993967, -1.72883926, -0.37194529],
       [-0.71789236, -0.24575431, -0.0886276 ]])

In [16]:
np.random.randint(10,20, size=(3, 4))
np.random.uniform(10,20, size=(3, 4))

array([[19.47301924, 15.91706255, 16.98876718, 13.2941841 ],
       [10.00974826, 14.25946354, 19.82815115, 16.14908819],
       [18.54238201, 16.48332193, 12.03263631, 12.98530815]])

In [17]:
# inf 和 nan
print(np.inf - np.inf)

nan


In [23]:
t = np.array([1,2,3,np.nan])
np.isnan(t)

array([False, False, False,  True])

In [33]:
# 统计函数
t = np.random.randint(10,20, size=(3, 4))
t.sum(axis = 1)

array([58, 54, 65])

In [39]:
t = np.arange(24).reshape(4,6)
t.mean()

11.5